language: python
python:
- '3.6'
cache: pip
install:
- pip install pipenv --upgrade
- pipenv install --dev
script:
- py.test -m "not ui" --cov-config .covconfig
deploy:
  provider: heroku
  api_key:
    secure: tnyUDdK+V1bVD/X6N7fS8CPYsxse9gMl6Jnt/G1PxtrRze7C5a5qL/CK1zE/2/yVIA0TuIZmpRQn1L8ViUshRf/hZ228NJToV0xCX1za0kXrMSOjIRNNX3uc4U7yYMc8y3RqDS4h4l2PK8pKbJJzFuwELnVXuNNylOfycuc811nbni5B1rearbj5ThAiU0KhnH1htoFhJqng1DK/1C3IJlM4xDXdfcYRaxpKYV1DgwxaDYiJIQtUYTSZ7mh4Cm2SEQI1GE/192JpQ+tQB1gGjASkGAkjbV9DGE6zQRnbbRb1Z0yparXMsdvKyElobTXEEBpfDMXlYy8ALgY9+3FrOIf5ntc2Gb6OTKTyfI3vl5trs8tnETCQd6AH4aje7fbBhawCECahYgY+Yy9NQsuRd83nbNtOJNJQD1wy5o5NtPLjbghRpdUcBxgp22Gc0pzIqhwO2/8lc8D03NZjDWj7zmSC/S/AVqzmjrAz73m6QUjamNvsiweq+uhB+hqEpdXtZhXqSZECL8/mR4SVh15OFYtZmh5M1CmOvKWT/4NQA/KqTSyp6EHCl3bgVAm8jFaReblSvvLR749SyOu9FC2StIe9tR4aJou/il8+L814xp9YKJFpf7xAUjsNVu060dA6TzjBlj3JN5vfGahT/6oE25tpa/SxtFdcZFiBcA96Zuk=
  app: shoptimizeme
after_success: coveralls
