language: python
python:
- '3.6'
cache: pip
install:
- pip install pipenv --upgrade
- pipenv install --dev
script:
- py.test -m "not ui" --cov-config .covconfig
deploy:
  provider: heroku
  api_key:
    secure: hxJQNvICpkLF7jkM0q9MRz0H+y3qwIB6aTCV5jhbiwmGFyQb+vMeAL97aiZLXRvgN8v8gdSbgGjw0SLC1/tarRA2NArEvr5mm+LFD7C+I6s1txU10g7HpsSfWmkdDZDb1DFyUqJhxBx7HI81GoteNtQj1+iXAO79u1DtaP3lLbJTDAsH0O8SkJqMwvJwEfxxQwE3k9EV1EV/j9O3gwLe2oJ5MMYUPx5omGkmivu95Z55/u7TCiNh4/XpgBxuNdlnMv9wRaxQIqtE1jktmDA4LLXJ5G+C/3u7xCxigMB3yD/ZFhbyhlYKcCcZVUFo64F0ngDLkIR44U6sCnHPQM8vpuROIjFOEIYkwVFhgr8xh2lBDYdyZ04VQR2fVM5cEdU5t1ChPRFEQV+LSQ2GmgDdWJnv3HR7RMAeCexhtdO53s+21+Jha/kU39s5l9Wd6UOvYtZP19qmb5XQktaZ+nWarmtV6JMxiG64CpeLVzjpiQnaoiLJJHigtsJodEa0JCRqv9En0pY3UkRwpIOPc+CpgKjM/SoKd5AFiXi3Y9V40Jg0qtgQNGhfFxIDSGF384lpXZbA0DKnhDjolckLoP3WxW9KDDSWLCkz9kL9P5le2Or3ByYYzswICFj4OQBJ1yli3qnA5MdUNAyBFJN3B177pLgDZTHN2alC1IGFy5O6jRY=
after_success: coveralls
