# Generated by Django 2.0 on 2018-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_grocerydiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerydiscount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocerydiscount',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
