# Generated by Django 2.0 on 2018-01-28 17:55

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_auto_20180128_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerydiscount',
            name='begins',
            field=models.DateField(default=datetime.datetime.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocerydiscount',
            name='ends',
            field=models.DateField(default=datetime.datetime.today()),
            preserve_default=False,
        ),
    ]
